#!/bin/sh
# Bring an rpm into the appropriate repo from the staging area
# 
########################################################################
# Change Log
# 04/11/14 shubes - changed invocation of qt-update-yum-repos
#                 - split out qt-check-sign-rpm script
#                 - split out qt-move-to-repo script
#                 - refactored
# 04/09/14 shubes - remove related binaries when staging srpm
# 12/09/13 shubes - added processing for logs
# 12/01/13 shubes - created
########################################################################

########################################################################
# process each build logs and its binary rpms

a6_stage_build_files(){

archdir=${staglog%/*}

while read wrotestring; do
  rpmfile=${wrotestring#Wrote: }
# there's a \r at the end of this string that we need to get rid of
  rpmfile=${rpmfile%.rpm*}
  rpmfile=${rpmfile}.rpm
  rpmfile=${rpmfile##*/}
  stagfile=$archdir/$rpmfile
  qt-check-sign-rpm    $stagfile
  qt-move-file-to-repo $stagfile
done << !EOF!
$(grep ^Wrote $staglog)
!EOF!
 
archdir=$(echo $archdir | sed -e "s|$stagdir/|$repodir/|")
touch $archdir/$flagfile

qt-move-file-to-repo $staglog
}

########################################################################
# main process begins here
#
me=${0##*/}
myver=v1.1
echo "$me - $myver started"

stagdir=/stage
repodir=/repos
flagfile=.needs-update

for stagfile in $(find $stagdir -name "*.src.rpm" ); do
  qt-check-sign-rpm    $stagfile
  qt-remove-binaries   $stagfile
  qt-move-file-to-repo $stagfile
done

for staglog in $(find $stagdir -name "*.buildlog.txt" ); do
  a6_stage_build_files
done

qt-update-yum-repos

echo "$me - ended"
exit 0
