#!/bin/sh
# Bring a file from the testing branch to the current tree,
# setting up the appropriate hard links et al.
# 
########################################################################
# Change Log
# 04/21/14 shubes - created from qt-move-file-to-repo
########################################################################

########################################################################
# main process begins here
#
me=${0##*/}
myver=v1.0

if [ -z "$1" ]; then
  echo "$me - usage: $me repofile"
  exit 1
elif [ ! -f "$1" ]; then
  echo "$me - file $1 not found"
  exit 2
fi

fromtree=testing
desttree=current
repodir=/repos
actdir=$repodir/active
arcdir=$repodir/archive/rpms

testfile=$1
filename=${testfile##*/}
anchor=$actdir/$filename
destfile=$(echo $testfile | sed -e "s|$fromtree|$desttree|")

ln $anchor $arcdir/$filename
ln $anchor $destfile
rm $testfile

echo "$me - $testfile promoted to current"

exit 0
