#!/bin/sh
#
# Create/update QMailToaster yum repositories
#####################################################################
# change log
# 04/11/14 shubes - changed to be run as a cron job
# 12/09/13 shubes - see if log files need to be excluded - they don't
# 12/06/13 shubes - only process repo if something has changed
# 12/02/13 shubes - modified to accept status as argument
# 11/24/13 shubes - migrated from qmailtoaster-plus to QMailToaster
# 08/22/09 shubes - created
#####################################################################

#####################################################################
# process each repo - $1 is full path to the flag file
#
a5_process_repo(){

flagfile=$1
repodir=${flagfile%/*}

echo "$me - processing $repodir"
rm $flagfile
createrepo --update --pretty $repodir 2>&1
}

#####################################################################
## begin main processing here
#
me=${0##*/}
myver=v1.2

echo "$me - $myver started"

for repoflag in $(find /repos/ -type f -name .needs-update); do
  a5_process_repo $repoflag
done

echo "$me - ended"
exit 0
