#!/bin/sh
#
# Create/update QMailToaster yum repositories
#####################################################################
# change log
# 12/09/13 shubes - exclude log files
# 12/06/13 shubes - only process repo if something has changed
# 12/02/13 shubes - modified to accept status as argument
# 11/24/13 shubes - migrated from qmailtoaster-plus to QMailToaster
# 08/22/09 shubes - created
#####################################################################

#####################################################################
# process each repo - $1 is full path to the repo directory
#
a5_process_repo(){

repodir=$1
echo "$me - processing $repodir"

createrepo --update --pretty --excludes "*.log" $repodir

echo ""
}

#####################################################################
## begin main processing here
#
me=${0##*/}
myver=v1.1
echo "$me $myver"

distrel_list="\
CentOS/5 \
CentOS/6 \
"
basedir=/repos/$1
if [ -z "$1" ]; then
  echo "$me what? (need to supply a name)"
  exit 1
elif [ ! -d  "$basedir" ]; then
  echo "$me - $basedir does not exist"
  exit 1
fi

a5_process_repo $basedir/nodist

for distrel in $distrel_list; do
  for repodir in $(find $basedir/$distrel -mindepth 1 -maxdepth 1 -type d); do
    a5_process_repo $repodir
  done
done

echo "$me - done"
exit 0
